version: 2

models:

  - name: sfdc_account_deal_size_segmentation
    columns:
      - name: account_id
        data_tests:
          - not_null
          - unique
      - name: close_date
        data_tests:
          - not_null
      - name: deal_size
        data_tests:
          - not_null

  - name: sfdc_accounts_xf
    description: '{{ doc("sfdc_accounts_xf") }}'
    columns:
      - name: account_id
        data_tests:
          - not_null
          - unique
      - name: account_name
        data_tests:
          - not_null
      - name: sales_segment
        description: Deprecated, please use division_sales_segment or tsp_max_hierarchy_sales_segment instead.
      - name: tsp_test_sales_segment
        description: Deprecated, please use tsp_max_hierarchy_sales_segment instead.
      - name: account_segment
        description: Deprecated, please use division_sales_segment instead.
      - name: ultimate_parent_sales_segment
        description: Sales segment of the parent of the account hierarchy.
      - name: ultimate_parent_account_segment
        description: Deprecated, please use ultimate_parent_sales_segment instead.

  - name: sfdc_lead_xf
    description: '{{ doc("sfdc_lead_xf") }}'
    columns:
      - name: lead_id
        data_tests:
          - not_null
          - unique


  - name: sfdc_lead_sources
    columns:
      - name: lead_source_id
        data_tests:
          - not_null
          - unique
      - name: initial_source
        data_tests:
          - not_null
      - name: initial_source_type
        data_tests:
          - not_null

  - name: sfdc_opportunity_xf
    description: This model contains meta information on each Salesforce opportunity enriched with stage, source, and user information. Note that `sales_segment` and `parent_segment` are derived from the Stamped Sales Segment for an opportunity and do not change over time. The current segmentation of an opportunity's account is available in `sfdc_accounts_xf`.
    columns:
      - name: opportunity_id
        data_tests:
          - not_null
          - unique
      - name: owner_id
        description: The SFDC ID of opportunity owner.
        data_tests:
            - not_null
      - name: order_type_current
        description: The most current state of the order type formula in SFDC.
      - name: parent_crm_account_sales_segment
        description: Maximum account sales segment within the account hierarchy.
        data_tests:
          - accepted_values:
              values: ['SMB', 'Mid-Market', 'Large', 'Unknown', 'PubSec', Null]
      - name: division_sales_segment_stamped
        description: Stamped version of the account division sales segment.
      - name: division_sales_segment
        description: Sales segment of the specific account.
      - name: ultimate_parent_sales_segment
        description: Sales segment of the parent of the account hierarchy.
      - name: sales_segment
        description: Deprecated, please use division_sales_segment or tsp_max_hierarchy_sales_segment instead.
      - name: parent_segment
        description: Deprecated, please use ultimate_parent_sales_segment instead.
      - name: segment
        description: Deprecated, please use division_sales_segment or tsp_max_hierarchy_sales_segment instead.
      - name: order_type_current
        description: The most current state of the order type formula in SFDC.
      - name: dr_partner_deal_type
        description: Map field from Lead object during conversion. Lead Field Name = [Partners] Deal Registration Type.
      - name: dr_partner_engagement
        description: This field Identified the engagement of the partner who registered the deal.

  - name: sfdc_users_xf
    columns:
      - name: user_id
        data_tests:
          - not_null
          - unique
      - name: role_name
        data_tests:
          - not_null:
              config:
                severity: warn
