version: 2

models:
  - name: gong_transcript_source
    description: transcript data from gongio
    columns:
      - name: call_id
  - name: gong_users_source
    description: user data from gongio
    columns:
      - name: id
      - name: gong_connect_enabled
      - name: meeting_consent_page_url
      - name: prevent_web_conference_recording
      - name: phone_number
      - name: prevent_email_import
      - name: emails_imported
      - name: telephony_calls_imported
      - name: manager_id
      - name: non_recorded_meetings_imported
      - name: extension
      - name: last_name
      - name: first_name
      - name: title
      - name: web_conferences_recorded
      - name: email_address
      - name: active
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: created
      - name: index 
      - name: workspace_id
      - name: sentence
      - name: speaker_id
      - name: topic
      - name: _fivetran_deleted
      - name: _fivetran_synced
  - name: gong_tracker_source
    description: tracker data from gongio
    columns:
      - name: tracker_id
        data_tests:
          - unique
          - not_null
      - name: affiliation 
      - name: created
      - name: tracker_name
      - name: part_of_question
      - name: said_at_interval
      - name: workspace_id
      - name: creation_user_id
      - name: said_at
      - name: updated
      - name: filter_query
      - name: updated_user_id
      - name: _fivetran_deleted
      - name: _fivetran_synced
  - name: gong_tracker_language_source
    description: tracker language data from gongio
    columns:
      - name: tracker_id
        data_tests:
          - unique
          - not_null
      - name: tracker_language 
      - name: include_related_forms
      - name: _fivetran_deleted
      - name: _fivetran_synced
  - name: gong_call_source
    description: call data from gongio
    columns:
      - name: id
      - name: url
      - name: media
      - name: custom_data
      - name: sdr_disposition
      - name: is_private
      - name: client_unique_id
      - name: direction
      - name: languages
      - name: scope
      - name: duration
      - name: title
      - name: meeting_url
      - name: systems
      - name: purpose
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: scheduled
      - name: media_video_url
      - name: company_question_count
      - name: non_company_question_count
      - name: started
      - name: media_audio_url
  - name: gong_call_content_action_item_source
    description: call content action item data from gongio
    columns:
      - name: call_id
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: snippet
  - name: gong_call_context_integration_source
    description: call context integration data from gongio
    columns:
      - name: call_id
      - name: object_id
      - name: name
  - name: gong_call_tracker_source
    description: call tracker data from gongio
    columns:
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: start_time
      - name: phrase
      - name: speaker_id
      - name: name
      - name: id
      - name: type
      - name: call_id
      - name: value
  - name: gong_call_topic_source
    description: call topic data from gongio
    columns:
      - name: call_id
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: duration
      - name: name
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: systems
      - name: object_type
      - name: timing
  - name: gong_call_interaction_source
    description: call interaction data from gongio
    columns:
      - name: call_id
      - name: name
      - name: _fivetran_deleted
      - name: _fivetran_synced
      - name: value_end_time
      - name: snippet_start_time
      - name: speaker_id
      - name: snippet