version: 2

sources:
  - name: gong
    database: RAW
    schema: gong
    loader: fivetran    
    loaded_at_field: _fivetran_synced

    quoting:
      database: true
      schema: false
      identifier: false
    
    tables:
      - name: transcript
      - name: tracker
      - name: tracker_language
      - name: call
      - name: call_content_action_item
      - name: call_context_integration
      - name: call_interaction
      - name: call_topic
      - name: call_tracker
      - name: users