version: 2

sources:
  - name: snapshots
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: snapshots
    loader: dbt
    loaded_at_field: dbt_updated_at
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: bizible_attribution_touchpoint_snapshots
      - name: bizible_touchpoint_snapshots
      - name: customers_db_customers_snapshots
      - name: customers_db_orders_snapshots
      - name: dim_subscription_snapshot
      - name: fct_available_to_renew_snapshot
      - name: fct_mrr_snapshot
      - name: fct_retention_parent_account_snapshot
      - name: gitlab_dotcom_application_settings_snapshots
      - name: gitlab_dotcom_gitlab_subscriptions_namespace_id_snapshots
      - name: gitlab_dotcom_gitlab_subscriptions_snapshots
      - name: gitlab_dotcom_members_snapshots
      - name: gitlab_dotcom_namespaces_snapshots
      - name: gitlab_dotcom_namespace_statistics_snapshots
      - name: gitlab_dotcom_namespace_settings_snapshots
      - name: gitlab_dotcom_namespace_root_storage_statistics_snapshots
      - name: gitlab_dotcom_projects_snapshots
      - name: gitlab_dotcom_project_statistics_snapshots
      - name: gitlab_dotcom_subscription_add_on_purchases_snapshots
      - name: mart_arr_snapshot
      - name: mart_retention_parent_account_snapshot
      - name: customers_db_licenses_snapshots
      - name: sfdc_account_snapshots
      - name: sfdc_bizible_attribution_touchpoint_snapshots
      - name: sfdc_bizible_touchpoint_snapshots
      - name: sfdc_contact_snapshots
      - name: sfdc_lead_snapshots
      - name: sfdc_opportunity_snapshots
      - name: sfdc_opportunity_product_snapshots
      - name: sfdc_user_snapshots
      - name: sfdc_sandbox_user_snapshots
      - name: workday_employee_directory_snapshots
      - name: workday_supervisory_org_snapshots
      - name: zuora_account_snapshots
      - name: zuora_amendment_snapshots
      - name: zuora_contact_snapshots
      - name: zuora_invoice_snapshots
      - name: zuora_invoiceitem_snapshots
      - name: zuora_product_rate_plan_charge_snapshots
      - name: zuora_chargemetrics_snapshots
      - name: zuora_product_rate_plan_charge_tier_snapshots
      - name: zuora_product_rate_plan_snapshots
      - name: zuora_product_snapshots
      - name: zuora_rateplan_snapshots
      - name: zuora_rateplancharge_snapshots
      - name: zuora_refund_snapshots
      - name: zuora_revenue_schedule_item_snapshots
      - name: zuora_subscription_snapshots
      - name: mart_available_to_renew_snapshot
      - name: mart_charge_snapshot
      - name: customers_db_leads_snapshots
      - name: gitlab_dotcom_users_snapshots
      - name: gitlab_dotcom_user_preferences_snapshots
      - name: gitlab_dotcom_user_details_snapshots
      - name: gitlab_dotcom_identities_snapshots
      - name: gitlab_dotcom_namespace_details_snapshots
      - name: rpt_ping_metric_totals_w_estimates_monthly_snapshot
      - name: rpt_event_xmau_metric_monthly_snapshot
      - name: dim_user_snapshot
        columns:
          - name: email
            description: User's email address
            meta:
              masking_policy: sensitive_pii_data_viewer
      - name: customers_db_billing_accounts_snapshots
      - name: job_profiles_snapshots
      - name: customers_db_billing_account_contacts_snapshots
      - name: customers_db_cloud_activations_snapshots
      - name: cost_centers_snapshots
      - name: workday_hcm_job_profiles_snapshots
      - name: workday_employee_mapping_snapshots
        description: Snapshot table tracking changes to employee mappings over time
        tests:              
          - dbt_utils.expression_is_true:
              expression: "NOT REGEXP_LIKE(greenhouse_candidate_id, '^[A-Za-z]')"
              config:
                severity: error
        columns:
          - name: greenhouse_candidate_id
            tests:
              - not_null