version: 2
 
models:
 - name: agreements_source
   description: Base model for agreements
 - name: requests_source
   description: Base model for requests
 - name: vendors_source
   description: Base model for vendors
   