version: 2
 
sources:
 - name: zip_sandbox
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: zip_sandbox
   loaded_at_field: uploaded_at
   loader: Airflow
   description: Zip Sandbox data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/20717)
 
   tables:
     - name: agreements
     - name: requests
     - name: vendors