version: 2

sources:
  - name: demo_architecture_portal
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: demo_architecture_portal
    loader: stitch

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: labs
      - name: ilt_users
      - name: redemptions