WITH source AS (	

   SELECT *	
   FROM {{ source('sheetload', 'cocreate_status_pipeline') }}	

), renamed AS (	

SELECT 
      company::varchar                                        AS company,  
      slack_channel::varchar                                  AS slack_channel,  
      tracking_issue::varchar                                 AS tracking_issue,
      cocreate_stage::varchar                                 AS cocreate_stage,
      contacted_in_function_of_leading_organizations::varchar AS contacted_in_function_of_leading_organizations,
      dri_csm_or_sa::varchar                                  AS dri_csm_or_sa,  
      list_of_sub_account_issues_interested::integer          AS list_of_sub_account_issues_interested,  
      list_of_parent_account_issues_interested::integer       AS list_of_parent_account_issues_interested,
      co_create_next_step_owner::varchar                      AS co_create_next_step_owner,  
      co_create_next_step_single_sentence::varchar            AS co_create_next_step_single_sentence,  
      last_update::varchar                                    AS last_update,  
      had_technical_onboarding::varchar                       AS had_technical_onboarding,
      onboarding_workshop_date::varchar                       AS onboarding_workshop_date,
      had_onsite::varchar                                     AS had_onsite,
      onsite_date::varchar                                    AS onsite_date,  
      engagement_details::varchar                             AS engagement_details,
      engagement_origin::varchar                              AS engagement_origin,  
      engagement_location::varchar                            AS engagement_location,  
      gitlab_devrel::varchar                                  AS gitlab_devrel,  
      gitlab_account_owner::varchar                           AS gitlab_account_owner,
      gitlab_ae_manager::varchar                              AS gitlab_ae_manager,  
      gitlab_solutions_architect::varchar                     AS gitlab_solutions_architect,
      gitlab_customer_success_manager::varchar                AS gitlab_customer_success_manager,  
      gitlab_csm_manager::varchar                             AS gitlab_csm_manager,
      gitlab_pm::varchar                                      AS gitlab_pm,  
      gitlab_on_site_engineer::varchar                        AS gitlab_on_site_engineer,  
      ps_details::varchar                                     AS ps_details,
      crm_account_id::varchar                                 AS crm_account_id,
      customer_contact::varchar                               AS customer_contact,
      customer_contact_email::varchar                         AS customer_contact_email,
      customer_engineers::varchar                             AS customer_engineers,
      co_create_artifacts::varchar                            AS co_create_artifacts,  
      co_create_artifacts_clickable_autogenerated::varchar    AS co_create_artifacts_clickable_autogenerated,
      crm_parent_account_id::varchar                          AS crm_parent_account_id,  
      customer_engineer_parent::varchar                       AS customer_engineer_parent,
      co_create_parent_artifacts::varchar                     AS co_create_parent_artifacts 
FROM source

)	

SELECT *	
FROM renamed	