version: 2

sources:
  - name: atlan
    database: GITLAB_ATLAN_USAGE_DATA
    schema: CUSTOMER_USAGE
    loader: atlan_snowflake_share
    # loaded_at_field: _sdc_batched_at

    quoting:
      database: true
      schema: false
      identifier: false

    # freshness:
      # warn_after: {count: 24, period: hour}
      # error_after: {count: 48, period: hour}

    tables:
      - name: gitlab_active_users
      - name: gitlab_feature_usage
      - name: gitlab_user_details
      - name: gitlab_event_details
      - name: gitlab_user_licenses_details