version: 2

models:
  - name: servicenow_prd_incident_source
    description: Incident data from service management system
    columns:
      - name: sys_id
        description: Unique identifier for incident records
        data_tests:
          - unique
          - not_null
      - name: rfc_value
      - name: reopened_time
      - name: severity
      - name: caller_id_value
      - name: sys_updated_by
      - name: sys_created_on
      - name: sys_domain_path
      - name: short_description
      - name: sys_class_name
      - name: sla_due
      - name: sys_created_by
      - name: state
      - name: assignment_group
      - name: contact_type
      - name: incident_state
      - name: sys_updated_on
      - name: impact
      - name: active
      - name: priority
      - name: opened_at
      - name: close_code
      - name: resolved_by
      - name: resolved_at
      - name: reassignment_count
      - name: close_notes
      - name: assigned_to
      
  - name: servicenow_prd_incident_task_source
    description: Tasks related to incidents
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: incident_id
        description: Reference to parent incident
      - name: short_description
      - name: state
      - name: assigned_to
      - name: assignment_group

  - name: servicenow_prd_problem_source
    description: Problem records from service management system
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: number
      - name: short_description
      - name: description
      - name: state
      - name: priority
      - name: impact
      - name: assigned_to
      - name: assignment_group
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: opened_at
      - name: closed_at
      - name: resolved_at
      - name: resolved_by
      - name: known_error
      - name: workaround
      - name: review_date
      - name: root_cause
      - name: fix_notes
      - name: category
      - name: subcategory
      - name: active
      - name: related_incidents
      - name: assigned_to_value
      - name: assignment_group_value

  - name: servicenow_prd_problem_task_source
    description: Tasks related to problems
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: problem_id
        description: Reference to parent problem
      - name: short_description
      - name: description
      - name: state
      - name: priority
      - name: assigned_to
      - name: assignment_group
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: due_date
      - name: work_notes
      - name: active
      - name: close_notes

  - name: servicenow_prd_sla_source
    description: Service Level Agreement data
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: task
        description: Reference to the task this SLA is applied to
      - name: task_type
      - name: sla_definition
      - name: start_time
      - name: end_time
      - name: time_left
      - name: percentage
      - name: duration
      - name: business_duration
      - name: pause_duration
      - name: pause_time
      - name: breach_time
      - name: stage
      - name: has_breached
      - name: active
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: schedule
      - name: timezone
      - name: planned_end_time
      - name: original_breach_time
      - name: business_time_left
      - name: business_percentage
      - name: pause_reason
      - name: pause_schedule
      - name: sys_class_name
      - name: agreement_type
      - name: sys_domain
      - name: pause_start
      - name: workflow_state
      - name: stop_trigger
      - name: start_time_conditions
      - name: business_calculated_on
      - name: created_triggers
      - name: priority
      - name: contract
      - name: work_notes
      - name: business_calendar
      - name: task_value

  - name: servicenow_prd_sys_user_source
    description: User data from the system
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: user_name
      - name: first_name
      - name: last_name
      - name: email
      - name: phone
      - name: mobile_phone
      - name: title
      - name: department
      - name: manager
      - name: location
      - name: company
      - name: active
      - name: locked_out
      - name: last_login
      - name: notification
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: sys_domain
      - name: sys_class_name
      - name: vip
      - name: time_zone
      - name: language
      - name: user_password
      - name: gender
      - name: street
      - name: city
      - name: state
      - name: country
      - name: zip

  - name: servicenow_prd_sys_user_group_source
    description: User group data from the system
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: name
      - name: description
      - name: manager
      - name: parent
      - name: active
      - name: type
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: sys_domain
      - name: include_members
      - name: roles
      - name: email
      - name: default_assignee
      - name: source
      - name: exclude_manager
      - name: cost_center

  - name: servicenow_prd_task_source
    description: Task data from the system
    columns:
      - name: sys_id
        data_tests:
          - unique
          - not_null
      - name: number
      - name: short_description
      - name: description
      - name: assignment_group
      - name: assigned_to
      - name: state
      - name: priority
      - name: impact
      - name: urgency
      - name: sys_created_on
      - name: sys_updated_on
      - name: sys_created_by
      - name: sys_updated_by
      - name: due_date
      - name: opened_at
      - name: closed_at
      - name: parent
      - name: work_notes
      - name: comments
      - name: close_notes
      - name: close_code
      - name: opened_by
      - name: closed_by
      - name: active
      - name: reassignment_count
      - name: approval
      - name: category
      - name: subcategory
      - name: escalation
      - name: contact_type
      - name: sys_class_name
      - name: company
      - name: location
      - name: business_service
      - name: cmdb_ci
      - name: caller_id
      - name: expected_start
      - name: follow_up
      - name: actual_start
      - name: actual_end
      - name: time_worked
      - name: delivery_plan
      - name: delivery_task
      - name: activity_due
      - name: business_duration
      - name: calendar_duration
      - name: made_sla
      - name: upon_approval
      - name: wait_for
      - name: correlation_id
      - name: sla_due
      - name: order