version: 2

models:
  - name: mailgun_events
    description: '{{ doc("mailgun_events") }}'
    columns:
      - name: domain
        description: '{{ doc("mailgun_domains") }}'
        data_tests:
          - not_null
      - name: id
        data_tests:
          - not_null
      - name: envelope_sender
      - name: envelope_targets
      - name: primary_dkim
      - name: message_headers_from
      - name: message_headers_message_id
      - name: message_headers_to
      - name: event
      - name: recipient_domain
      - name: recipient_provider
      - name: log_level
      - name: recipient
      - name: delivery_status_code
      - name: delivery_status_mx-host
      - name: delivery_status_description
      - name: delivery_status_attempt_no
      - name: delivery_status_message
      - name: timestamp
      - name: campaigns
      - name: reason
      - name: delivery_status_bounce_code
      - name: delivery_status_bounce_type
      - name: geolocation_region
      - name: geolocation_city
      - name: geolocation_timezone
      - name: geolocation_country