version: 2

models:
  - name: rpt_top_issues_by_arr
    description: '{{ doc("rpt_top_issues_by_arr") }}'
    columns:
      - name: issue_id
        description: Unique identifier per issue.
        tests:
          - not_null
          - unique
      - name: issue_iid
        description: GitLab issue IID from the engineering issues table. This tends to be what is used in the URL.
      - name: issue_title
        description: Title of the GitLab engineering issue
      - name: mentions
        description: Total number of support ticket mentions for this issue
      - name: unique_customers
        description: Number of distinct customers who mentioned this issue
      - name: arr_rank
        description: |
          Ranking of issues by total customer ARR (1 = highest ARR). 
          Calculated only after filtering out confidential issues to ensure continuous ranking.
        tests:
          - not_null
      - name: mentioning_customer_names
        description: Comma-separated list of customer names who mentioned this issue
      - name: support_ticket_ids
        description: Comma-separated list of Zendesk ticket IDs that reference this issue
      - name: state
        description: Current state of the issue (opened/closed)
      - name: issue_type
        description: Type of issue (Bug/Feature/Enhancement) derived from labels or issue_type field
      - name: severity
        description: Issue severity label (S1/S2/S3/S4 or undefined)
      - name: priority
        description: Issue priority label (P1/P2/P3/P4 or undefined)
      - name: milestone
        description: GitLab milestone assigned to the issue (or undefined)
      - name: weight
        description: Issue weight/story points assigned to the issue
      - name: section
        description: GitLab section label indicating which product section owns the issue
      - name: group_name
        description: GitLab group label indicating which engineering group owns the issue
      - name: days_open
        description: Number of days the issue has been open (from creation to close date or current date)
      - name: issue_url
        description: Direct URL link to the GitLab issue
      - name: issue_created_at
        description: Timestamp when the GitLab issue was created
      - name: issue_updated_at
        description: Timestamp when the GitLab issue was last updated
      - name: issue_closed_at
        description: Timestamp when the GitLab issue was closed (null if still open)
      - name: first_mentioned_date
        description: Date when this issue was first mentioned in a customer support ticket
      - name: last_mentioned_date
        description: Date when this issue was most recently mentioned in a customer support ticket
      - name: project_path
        description: GitLab project path where the issue resides (e.g., gitlab, omnibus-gitlab, gitlab-runner)
