version: 2

models:
    - name: tableau_fivetran_workbook_source
      description: "{{ doc('tableau_fivetran_workbook') }}"
      
      columns:
        - name: workbook_id
          description: unique identifier for the workbook
          data_tests:
              - unique
              - not_null
        - name: owner_id
          description: identifier of the user who owns the workbook
        - name: project_id
          description: identifier of the project the workbook belongs to
        - name: show_tab
          description: boolean indicating if the workbook tab should be shown
        - name: created_at
          description: timestamp of when the workbook was created
        - name: webpage_url
          description: url of the webpage where the workbook can be accessed
        - name: workbook_description
          description: text description of the workbook
        - name: location_id
          description: identifier of the location where the workbook is stored
        - name: location_type
          description: type of location where the workbook is stored (e.g., project, personal)
        - name: location_name
          description: name of the location where the workbook is stored
        - name: updated_at
          description: timestamp of when the workbook was last updated
        - name: workbook_size
          description: size of the workbook in bytes
        - name: default_view_id
          description: identifier of the default view for the workbook
        - name: workbook_name
          description: name of the workbook
        - name: workbook_content_url
          description: url path to access the workbook's content
   
    - name: tableau_fivetran_data_source_source
      description: "{{ doc('tableau_fivetran_data_source') }}"
      
      columns:
        - name: data_source_id
          description: unique identifier for the data source
          tests:
            - unique
            - not_null
        - name: owner_id
          description: id of the data source owner
        - name: project_id
          description: id of the project
        - name: has_extract
          description: data source has an extract
        - name: is_certified
          description: data source is certified
        - name: created_at
          description: timestamp of when the data source was created        
        - name: data_source_description
          description: description of the data source
        - name: use_remote_query
          description: reports usage of a remote query for the data source
        - name: data_source_updated_at
          description: timestamp of when the data source was last updated
        - name: data_source_name
          description: name of the data source
        - name: data_source_content_url
          description: url of the content
        - name: webpage_url
          description: url of the webpage

    - name: tableau_fivetran_project_source
      description: "{{ doc('tableau_fivetran_project') }}"
      
      columns:
        - name: project_id
          description: Unique identifier for the project
          tests:
            - unique
            - not_null
        - name: controlling_permissions_project_id
          description: Identifier of the project that controls permissions for this project
        - name: owner_id
          description: Identifier of the user or group that owns this project
        - name: parent_project_id
          description: Identifier of the parent project
        - name: created_at
          description: Timestamp indicating when the project was created
        - name: project_description
          description: Text field containing a description of the project
        - name: content_permission
          description: Indicates the level of content permission for the project
        - name: updated_at
          description: Timestamp indicating when the project was last updated
        - name: project_name
          description: The name of the project
    
    - name: tableau_fivetran_extract_refresh_task_source
      description: "{{ doc('tableau_fivetran_extract_refresh_task') }}"
        
      columns:
        - name: schedule_id
          description: unique identifier for the schedule
          tests:
            - unique
            - not_null
        - name: schedule_frequency_details_interval_weekday
          description: details of the schedule frequency interval weekday
        - name: datasource_id
          description: id of the associated data source
        - name: workbook_id
          description: id of the associated workbook
        - name: schedule_next_run_at
          description: timestamp of the next scheduled run
        - name: schedule_frequency
          description: frequency of the schedule
        - name: priority
          description: priority of the schedule
        - name: schedule_type
          description: type of the schedule
        - name: schedule_frequency_details_start
          description: start details of the schedule frequency
        - name: consecutive_failed_count
          description: count of consecutive failed runs