version: 2

sources:
  - name: tableau_fivetran
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}' 
    schema: tableau_fivetran
    loader: Fivetran
    loaded_at_field: _FIVETRAN_SYNCED

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: workbook
        description: "{{ doc('tableau_fivetran_workbook') }}"
      
      - name: data_source
        description: "{{ doc('tableau_fivetran_data_source') }}"
      
      - name: project
        description: "{{ doc('tableau_fivetran_project') }}"
     
      - name: extract_refresh_task
        description: "{{ doc('tableau_fivetran_extract_refresh_task') }}"
          