version: 2

sources:
  - name: coupa
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: coupa
    loader: Fivetran
    
    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: order_line
      - name: order_header
      - name: supplier
      - name: commodity
      - name: account
