version: 2

models:
  - name: ent_sfdc_geo_pubsec_segment
    description: A user entitlement table based on user's Geo segment in Salesforce. It is used for row level security in Tableau. We have created a new geo_pubsec_segment column to align with the FY26 launch which brings the PubSec geo into Amer - the addition of this column will allow analysts to use it as the join key - subsequently allowing PubSec access to only people with a geo of Amer and a sales segment of PubSec.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - user_email
            - geo_pubsec_segment
    columns:
      - name: user_email
        data_tests: 
            - not_null
      - name: geo_pubsec_segment
        data_tests: 
            - not_null
      - name: entitlement_basis

  - name: ent_sfdc_account_manager_hierarchy
    description: A model that captures account entitlements based on management hierarchy and geographical access rules. It combines direct ownership relationships (including manager chain up to 3 levels) with geo-based access permissions, ensuring users who are account owners or in their management chain have appropriate access while maintaining separate geo-based access for non-owners.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dim_crm_account_id
            - user_email
            - entitlement_basis
    columns:
      - name: dim_crm_account_id
        description: The unique identifier for the CRM account
        data_tests:
          - not_null
      - name: user_email
        description: The email address of the user with account access
        data_tests:
          - not_null
      - name: geo_pubsec_segment
        description: The geographical or public sector segment associated with the account access
      - name: entitlement_basis
        description: The basis for the entitlement (either 'account_ownership' for direct/management chain access or 'geo' for geographical access)
        data_tests:
          - not_null