version: 2

models:
  - name: snowflake_show_roles_source
    description: Source layer for all snapshots of Snowflake roles.
  - name: snowflake_show_users_source
    description: Source layer for all snapshots of Snowflake users.
  - name: snowflake_query_history_source
    description: Source layer for all query history.  Column documentation can be found at https://docs.snowflake.com/en/sql-reference/account-usage/query_history.html#columns
  - name: snowflake_non_team_member_user_type_source
    description: A table built from a seed file to map a division, department, and user type to all snowflake users that are not team members.
    columns:
      - name: user_name
        description: The snowflake user name.  Used to relate to query activity
        data_tests:
          - unique
          - not_null
      - name: user_type
        description: A categorization used to group the snowflake users, primarily to differentiate between team members and application role types.
      - name: division
        description: The cost center division
      - name: department
        description: The cost center department
  - name: snowflake_warehouse_metering_history_source
    description: A table derived from the account [warehouse_metering_history_source view](https://docs.snowflake.com/en/sql-reference/functions/warehouse_metering_history) in Snowflake.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - warehouse_metering_start_at
            - warehouse_id
    columns:
      - name: warehouse_metering_start_at
        description: '{{ doc("warehouse_metering_start_at") }}'
        data_tests:
          - not_null
      - name: warehouse_metering_end_at
        description: '{{ doc("warehouse_metering_end_at") }}'
      - name: warehouse_id
        description: '{{ doc("warehouse_id") }}'
        data_tests:
          - not_null
      - name: warehouse_name
        description: '{{ doc("warehouse_name") }}'
      - name: credits_used_total
        description: '{{ doc("credits_used_total") }}'
      - name: credits_used_compute
        description: '{{ doc("credits_used_compute") }}'
      - name: credits_used_cloud_services
        description: '{{ doc("credits_used_cloud_services") }}'

  - name: snowflake_contract_rates_source
    description: A table built from a seed file to record the negotiated rate of snowflake credits.
    columns:
      - name: contract_rate_effective_date
        description: The date the rate became effective
      - name: contract_rate
        description: The dollar rate for snowflake credits.
  - name: snowflake_tables_source
    description: A view to `snowflake.account_usage.accounts` to be introduced into our transformation layer
  - name: snowflake_databases_source
    description: A view to `snowflake.account_usage.databases` to be introduced into our transformation layer

  - name: snowflake_automatic_clustering_history_source
    description: "This model contains information about Snowflake automatic clustering usage history. https://docs.snowflake.com/en/sql-reference/account-usage/automatic_clustering_history"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - clustering_start_at
            - table_id
    columns:
      - name: clustering_start_at
        description: "Start of the specified time range"
      - name: clustering_end_at
        description: "End of the specified time range"
      - name: credits_used
        description: "Number of credits billed for automatic clustering during the START_TIME and END_TIME window"
      - name: bytes_reclustered
        description: "Number of bytes reclustered during the START_TIME and END_TIME window"
      - name: rows_reclustered
        description: "Number of rows reclustered during the START_TIME and END_TIME window"
      - name: table_id
        description: "Internal/system-generated identifier for the table"
      - name: table_name
        description: "Name of the table"
      - name: schema_id
        description: "Internal/system-generated identifier for the schema that contains the table"
      - name: schema_name
        description: "Name of the schema that contains the table"
      - name: database_id
        description: "Internal/system-generated identifier for the database that contains the table"
      - name: database_name
        description: "Name of the database that contains the table"
      - name: instance_id
        description: "Internal/system-generated identifier for the instance which the object belongs to"

  - name: snowflake_cortex_functions_usage_history_source
    description: >
      Source model for Snowflake Cortex functions usage history. This model captures data about 
      Cortex AI function executions, including timing, resource usage, and token consumption.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - cortex_function_start_at
            - cortex_function_name
            - cortex_model_name
            - warehouse_id
    columns:
      - name: cortex_function_start_at
        description: Timestamp when the Cortex function execution started        
      - name: cortex_function_end_at
        description: Timestamp when the Cortex function execution completed        
      - name: cortex_function_name
        description: Name of the Cortex function that was executed        
      - name: cortex_model_name
        description: Name of the AI model used by the Cortex function        
      - name: warehouse_id
        description: ID of the warehouse that processed the Cortex function execution        
      - name: cortex_function_token_credits
        description: Number of token credits consumed by the Cortex function execution        
      - name: cortex_function_tokens
        description: Count of tokens processed during the Cortex function execution

  - name: snowflake_cortex_functions_query_usage_history_source
    description: >
      Source model that contains data about Snowflake Cortex functions usage history.
      This model pulls data from the Snowflake account usage view 'cortex_functions_query_usage_history'
      and provides information about queries that use Cortex AI functions, including token usage and costs.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - query_id
            - cortex_function_name
            - cortex_model_name
    columns:
      - name: query_id
        description: Unique identifier for the query that used Cortex functions      
      - name: warehouse_id
        description: Identifier for the warehouse that executed the query
      - name: cortex_model_name
        description: Name of the Cortex AI model used in the query
      - name: cortex_function_name
        description: Name of the specific Cortex function called in the query
      - name: cortex_function_tokens
        description: Number of tokens consumed by the Cortex function call
      - name: cortex_function_token_credits
        description: Cost in credits for the tokens consumed by the Cortex function