version: 2
 
models:
 - name: hackerone_source
   description: Base model for hackerone
   columns:
     - name: id
       description: Unique identifier
     - name: state
       description: The state of the bounty issue
     - name: created_at
       description: Timestamp of issue creation
     - name: bounties_array
       description: Information of the bounty 
     - name: uploaded_at
       description: Timestamp when the record is last updated at