version: 2
 
sources:
 - name: hackerone
   database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
   schema: hackerone
   loaded_at_field: uploaded_at
   loader: Airflow
   description: HackerOne data [Original Issue](https://gitlab.com/gitlab-data/analytics/-/issues/19639)
 
   tables:
     - name: reports