version: 2

models:
  - name: monthly_hg_technographics_by_account
    description: Monthly snapshot data for accounts with HG Insights Technographic data. Unique at crm_account_id | snapshot_month
  - name: monthly_stage_usage_by_account
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dim_crm_account_id
            - snapshot_month
  - name: monthly_stage_usage_by_account_ultimate
    description: monthly_stage_usage_by_account filtered to only show Ultimate namespaces / instances.
  - name: monthly_stage_usage_by_namespace
    description: Product stage usage metrics for free and paid ultimate parent namespaces by month
    columns:
      - name: primary_key
        data_tests:
          - not_null
          - unique
  - name: monthly_stage_usage_by_subscription
    description: Product usage metrics by the original subscription_id
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - dim_subscription_id_original
            - snapshot_month
  - name: prep_saas_flattened_metrics
    description: >-
      Intermediary model used to create monthly_stage_usage_by_namespace.
      It flattens the SaaS metrics from `prep_saas_usage_ping_namespace`.
      By doing this step in a separate model from `prep_saas_usage_ping_namespace` we get performance gains.
  - name: pte_scores
    description: Propensity to expand by at least 10% in the next 3 months. All Salesforce accounts are scored and updated monthly (excludes Russian and Belarusian accounts). Table is additive, with new scores added monthy. Uniqueness of table is at CRM_ACCOUNT_ID || SCORE_DATE
    columns:
      - name: score
        description: 0-1 value representing the likelihood to expand. For example, a value of 0.61 would mean a 61% likelihood to expand in the next 3 months
      - name: socre_date
        description: date on which the scores were generated
      - name: decile
        description: 1-10 value representing the scoring decile the record falls into. 1 = Top 10% of scores; 10 = Bottom 10% of scores
      - name: importance
        description: 1-100 value which weights the score decile and the ARR decile of an account. The higher the value the more likely for a large ARR expansion.
      - name: score_group
        description: Condenses the importance score into a 1-5 value. The higher the value the more likely for a large ARR expansion.
      - name: insights
        description: Top 5 prescriptive insights that can be done to raise the score of an account. If less than 5 presciptions available, explanatory insights are provided.
  - name: ptc_scores
    description: Propensity to churn or contract by at least 10% in the next 6 months. All Salesforce accounts > 100 USD ARR are scored and updated monthly (excludes Russian and Belarusian accounts).  
    columns:
      - name: score
        description: 0-1 value representing the likelihood to contract/churn. For example, a value of 0.61 would mean a 61% likelihood to contract/churn in the next 6 months
      - name: socre_date
        description: date on which the scores were generated
      - name: decile
        description: 1-10 value representing the scoring decile the record falls into. 1 = Bottom 10% of scores; 10 = Top 10% of scores
      - name: importance
        description: 1-100 value which weights the score decile and the ARR decile of an account. The lower the value, the more likely a high amount of ARR is to contract/churn from account.
      - name: score_group
        description: Condenses the importance score into a 1-5 value. The lower the value, the more likely a high amount of ARR is to contract/churn from account.
      - name: insights
        description: Top 5 explanatory insights for an account.
  - name: ptpt_scores
    description: The propensity to purchase Premium or Ultimate in the next 40 days for all namespaces currently in an active trail.
    columns:
      - name: score
        description: 0-1 value representing the likelihood to purchase. For example, a value of 0.61 would mean a 61% likelihood to purchase in the next 40 days
      - name: socre_date
        description: date on which the scores were generated
      - name: decile
        description: 1-10 value representing the scoring decile the record falls into. 1 = Top 10% of scores; 10 = Bottom 10% of scores
      - name: score_group
        description: Condenses the score into a 1-5 value. The higher the value, the more likely the namespace is to purchase.
      - name: insights
        description: Top 5 presciptive and explanatory insights for an namespace.
  - name: namespace_segmentation_scores
  - name: model_mart_crm_account_id
    description: >-
      Summarises per account and score date the scores given by the PtE and PtC models.
      It also solves discrepancies when the score of PtC = 1 and the score of PtE = 5 for the same score date, meaning that the account is highly likely to expand and contract at the same time.
      This is done by lowering or upping the score with the lowest distance to the score mean relative to its standard deviation.
      If the score with the lowest variance is the PtC, then the score will go from 1 to 2.
      If the score with the lowest variance is the PtE, then the score will go from 5 to 4.
  - name: ptpf_scores
    description: The propensity to purchase Premium or Ultimate in the next 6 months for namespaces currently under the Free plan. All SaaS Group Namespaces that have not been a paid account in the last 45 days are scored in this model.
    columns:
      - name: score
        description: 0-1 value representing the likelihood to purchase. For example, a value of 0.61 would mean a 61% likelihood to purchase in the next 6 months
      - name: score_date
        description: date on which the scores were generated
      - name: decile
        description: 1-10 value representing the scoring decile the record falls into. 1 = Top 10% of scores; 10 = Bottom 10% of scores
      - name: score_group
        description: Condenses the score into a 1-5 value. The higher the value, the more likely the namespace is to purchase.
      - name: insights
        description: Top 5 presciptive and explanatory insights for an namespace.
  - name: model_mart_crm_opportunity_id
    description: >-
      Summarises per opportunity and score date the scores given by the opportunity forecasting model.
    columns:
      - name: forecast_score_date
        description: date on which the forecasts were generated
      - name: forecasted_days_remaining
        description: Forecasted number of days remaining until close-won
      - name: forecasted_close_won_date
        description: Forecasted close-won date
      - name: forecasted_close_won_quarter
        description: Forecasted close-won quarter
      - name: forecasted_score_group
        description: Forecasted number of days remaining until close-won bucketed
      - name: forecast_insights
        description: Top insights about how the model arrived at its forecast for that opportunity
  - name: map_free_instances_to_crm_account_prep
    description: >-
      Maps Free Self-Managed instances to CRM accounts.
      It does so in a 3 stage process:
        1. Tries to join the host_name of the instance to the account domain registered in SFDC.
        2. If above does not work, tries to extract the company name from the host_name and join it to the company name in SFDC
        3. If above does not work, joins the host_name to the email address domain of leads associated to accounts.
      This model runs every Tuesday. If the run is skipped, will try to run on the next day.
    columns:
      - name: host_name
        description: host_name of the Free Self-Managed instance
      - name: host_name_chopped
        description: Removes unwanted prefixes of the host_name, like 'gitlab', 'git.lab.', ...
      - name: extracted_name
        description: Company name inferred from the host_name
      - name: extracted_name_cleaned
        description: extracted_name with only numerical and alphabetic characters.
      - name: matched_dim_crm_account_id
        description: dim_crm_account_id associated with the host_name
      - name: matched_crm_account_name
        description: CRM account name associated with the host_name
      - name: match_count
        description: Number from 1 to 4 indentifying when the match was found. 1 for account domain matches, 2 for company name matches, 3 for company name matches while only leaving numerical and alphabetic characters and 4 for email domain address matches.
      - name: match_quality
        description: Describe the estimated quality of the match. High for match_count of 1 (account domain), Medium for match counts of 2 and 3 (company name), and Low for match count of 4 (email domain).
      - name: match
        description: String that made the match between host_name and the CRM account. Mainly used for debugging/explanatory purposes.
      - name: is_educational
        description: Whether the host_name is estimated to be an educational installation (for example, an university)
      - name: is_ip
        description: Whether the host_name is an ip address.
      - name: last_date_host_name_seen
        description: Last date the host_name has been seen.
      - name: processed_date
        description: Last time the host_name has been processed for matching.
  - name: map_free_instances_to_crm_account
    description: >-
      Maps Free Self-Managed instances to CRM accounts, building upon the `map_free_instances_to_crm_account_prep` by adding the Claude reconciled host_names in sheetload_hostnames_to_accounts.
      It first uses the matches found in `sheetload_hostnames_to_accounts`, and then adds all the matches from `map_free_instances_to_crm_account_prep`.
      As of now the fields host_name_chopped, extracted_name, extracted_name_cleaned, match_count, match_quality, match, is_educational, is_ip, last_date_host_name_seen and processed_date are NULL for the matches coming from `sheetload_hostnames_to_accounts`.
    columns:
      - name: host_name
        description: host_name of the Free Self-Managed instance.
        data_tests:
          - not_null
          - unique
      - name: host_name_chopped
        description: Removes unwanted prefixes of the host_name, like 'gitlab', 'git.lab.', ... NULL for `source = Claude`
      - name: extracted_name
        description: Company name inferred from the host_name.  NULL for `source = Claude`
      - name: extracted_name_cleaned
        description: extracted_name with only numerical and alphabetic characters. NULL for `source = Claude`.
      - name: matched_dim_crm_account_id
        description: dim_crm_account_id associated with the host_name
      - name: matched_crm_account_name
        description: CRM account name associated with the host_name
      - name: match_count
        description: Number from 1 to 4 indentifying when the match was found. 1 for account domain matches, 2 for company name matches, 3 for company name matches while only leaving numerical and alphabetic characters and 4 for email domain address matches. NULL for `source = Claude`.
      - name: match_quality
        description: Describe the estimated quality of the match. High for match_count of 1 (account domain), Medium for match counts of 2 and 3 (company name), and Low for match count of 4 (email domain). NULL for `source = Claude`.
      - name: match
        description: String that made the match between host_name and the CRM account. Mainly used for debugging/explanatory purposes. NULL for `source = Claude`.
      - name: is_educational
        description: Whether the host_name is estimated to be an educational installation (for example, an university). NULL for `source = Claude`.
      - name: is_ip
        description: Whether the host_name is an ip address. NULL for `source = Claude`.
      - name: last_date_host_name_seen
        description: Last date the host_name has been seen. NULL for `source = Claude`.
      - name: processed_date
        description: Last time the host_name has been processed for matching. NULL for `source = Claude`.
      - name: source
        description: Whether the match comes from the Algorithm Reconciliation or the Claude mapping.