version: 2

models:
  - name: ecosystems_document_source
    description: '{{ doc("ecosystems_document") }}'
    columns:
      - name: account_name
        description: '{{ doc("ecosystems_account_name") }}'
        data_tests:
          - not_null
      - name: collaborators
        description: '{{ doc("ecosystems_collaborators") }}'
      - name: crm_account_id
        description: '{{ doc("ecosystems_crm_account_id") }}'
      - name: crm_account_name
        description: '{{ doc("ecosystems_crm_account_name") }}'
      - name: crm_account_owner_email
        description: '{{ doc("ecosystems_crm_account_owner_email") }}'
      - name: crm_account_phone
        description: '{{ doc("ecosystems_crm_account_phone") }}'
      - name: crm_opportunity_id
        description: '{{ doc("ecosystems_crm_opportunity_id") }}'
      - name: crm_opportunity_name
        description: '{{ doc("ecosystems_crm_opportunity_name") }}'
      - name: crm_opportunity_owner_email
        description: '{{ doc("ecosystems_crm_opportunity_owner_email") }}'
      - name: crm_opportunity_phone
        description: '{{ doc("ecosystems_crm_opportunity_phone") }}'
      - name: is_demo
        description: '{{ doc("ecosystems_is_demo") }}'
      - name: document_name
        description: '{{ doc("ecosystems_document_name") }}'
        data_tests:
          - not_null
      - name: document_status
        description: '{{ doc("ecosystems_document_status") }}'
      - name: document_id
        description: '{{ doc("ecosystems_document_id") }}'
        data_tests:
          - not_null
          - unique
      - name: update_history_created_at
        description: '{{ doc("ecosystems_update_history_created_at") }}'
      - name: update_history_created_by_id
        description: '{{ doc("ecosystems_update_history_created_by_id") }}'
      - name: update_history_created_by_username
        description: '{{ doc("ecosystems_update_history_created_by_username") }}'
      - name: update_history_last_updated_at
        description: '{{ doc("ecosystems_update_history_last_updated_at") }}'
      - name: update_history_updated_by_id
        description: '{{ doc("ecosystems_update_history_updated_by_id") }}'
      - name: update_history_updated_by_username
        description: '{{ doc("ecosystems_update_history_updated_by_username") }}'
      - name: uploaded_at
        description: '{{ doc("ecosystems_uploaded_at") }}'
        data_tests:
          - not_null
  - name: ecosystems_collaborative_value_assessment_source
    description: '{{ doc("ecosystems_cva") }}'
    columns:
      - name: account_name 
        description: '{{ doc("ecosystems_account_name") }}'
        data_tests:
          - not_null
      - name: active_external_collaborator 
        description: '{{ doc("ecosystems_active_external_collaborator") }}'
      - name: active_internal_collaborator 
        description: '{{ doc("ecosystems_active_internal_collaborator") }}'
      - name: active_partner_collaborator 
        description: '{{ doc("ecosystems_active_partner_collaborator") }}'
      - name: crm_opportunity_id 
        description: '{{ doc("ecosystems_crm_opportunity_id") }}'
      - name: collaborators 
        description: '{{ doc("ecosystems_collaborators") }}'
      - name: count_of_value_drivers_modified 
        description: '{{ doc("ecosystems_count_of_value_drivers_modified") }}'
      - name: is_discovery_modified
        description: '{{ doc("ecosystems_is_discovery_modified") }}'
      - name: document_id 
        description: '{{ doc("ecosystems_document_id") }}'
      - name: effectiveness_score
        description: '{{ doc("ecosystems_effectiveness_score") }}'
      - name: does_include_discovery
        description: '{{ doc("ecosystems_does_include_discovery") }}'
      - name: is_investment_modified
        description: '{{ doc("ecosystems_is_investment_modified") }}'
      - name: is_demo
        description: '{{ doc("ecosystems_is_demo") }}'
      - name: updated_at,
        description: '{{ doc("ecosystems_updated_at") }}'
      - name: latest_editor 
        description: '{{ doc("ecosystems_latest_editor") }}'
      - name: models_edits 
        description: '{{ doc("ecosystems_models_edits") }}'
      - name: presentation_name 
        description: '{{ doc("ecosystems_presentation_name") }}'
        data_tests:
          - not_null
      - name: viewer_logs 
        description: '{{ doc("ecosystems_viewer_logs") }}'
      - name: uploaded_at 
        description: '{{ doc("ecosystems_uploaded_at") }}'