version: 2

sources:
  - name: clari
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: clari
    loader: Airflow
    loaded_at_field: uploaded_at

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: net_arr
      - name: new_logo

  - name: clari_static
    database: '{{ env_var("SNOWFLAKE_STATIC_DATABASE") }}'
    schema: sensitive
    tables:
      - name: wk_sales_clari_net_arr_forecast_historical
        freshness: null
