version: 2

models:
  - name: wk_servicenow_prd_incident
    description: "Incident data from ServiceNow production environment"
  - name: wk_servicenow_prd_incident_task
    description: "Incident tasks from ServiceNow production environment"
  - name: wk_servicenow_prd_problem
    description: "Problem records from ServiceNow production environment"
  - name: wk_servicenow_prd_problem_task
    description: "Problem tasks from ServiceNow production environment"
  - name: wk_servicenow_prd_sla
    description: "Service Level Agreement data from ServiceNow production environment"
  - name: wk_servicenow_prd_sys_user
    description: "User data from ServiceNow production environment"
  - name: wk_servicenow_prd_sys_user_group
    description: "User group data from ServiceNow production environment"
  - name: wk_servicenow_prd_task
    description: "Task data from ServiceNow production environment"
  - name: wk_gitlab_dotcom_incident_management_issuable_escalation_statuses
    description: "Incident Management Issuable Escalation Statuses data from GitLab.com"
  - name: wk_gitlab_dotcom_incident_management_timeline_event_tag_links
    description: "Incident Management Timeline Event Tag Links data from GitLab.com"
  - name: wk_gitlab_dotcom_incident_management_timeline_event_tags
    description: "Incident Management Timeline Event Tags data from GitLab.com"
  - name: wk_gitlab_dotcom_incident_management_timeline_events
    description: "Incident Management Timeline Events data from GitLab.com"