version: 2

models:
  - name: mart_user_request
    description: '{{ doc("mart_user_request") }}'
    columns:
      - name: primary_key
        description: >-
          Primary key of mart_user_request. It is at the grain of the user request
          (combination of the issue_id or epic_id depending on where the request was done) and
          the links in those requests (combination of opp_id, account_id and zendesk ticket_id)
        data_tests:
          - not_null
          - unique
      - name: issue_id
        description: The identifier of the GitLab issue containing the user request, if applicable.
      - name: epic_id
        description: The identifier of the GitLab epic containing the user request, if applicable.
      - name: user_request_in
        description: Indicates whether the user request is in an issue, an epic, or both.
      - name: link_type
        description: The type of link between the user request and the CRM data (account, opportunity, or Zendesk ticket).
      - name: dim_crm_opportunity_id
        description: The identifier of the CRM opportunity linked to this user request, if any.
      - name: dim_crm_account_id
        description: '{{ doc("dim_crm_account_id") }}'
        data_tests:
          - not_null
      - name: dim_ticket_id
        description: The identifier of the Zendesk support ticket linked to this user request, if any.
      - name: request_priority
        description: The numerical priority value assigned to this request by the customer or internal stakeholder.
      - name: is_request_priority_empty
        description: Boolean flag indicating whether the request priority field is empty.
      - name: link_last_updated_date
        description: Date when the link between the user request and CRM data was last updated.
      - name: link_last_updated_month
        description: Month when the link between the user request and CRM data was last updated.
      - name: crm_opportunity_link
        description: URL link to the CRM opportunity in Salesforce.
      - name: crm_account_link
        description: URL link to the CRM account in Salesforce.
      - name: ticket_link
        description: URL link to the Zendesk support ticket.
      - name: issue_epic_title
        description: The title of the issue or epic containing the user request.
      - name: issue_epic_url
        description: URL link to the issue or epic in GitLab.
      - name: issue_epic_created_at
        description: Timestamp when the issue or epic was created.
      - name: issue_epic_created_date
        description: Date when the issue or epic was created.
      - name: issue_epic_created_month
        description: Month when the issue or epic was created.
      - name: issue_epic_state_name
        description: The current state of the issue or epic (open, closed, etc.).
      - name: issue_epic_closed_at
        description: Timestamp when the issue or epic was closed, if applicable.
      - name: issue_epic_closed_date
        description: Date when the issue or epic was closed, if applicable.
      - name: issue_epic_closed_month
        description: Month when the issue or epic was closed, if applicable.
      - name: milestone_title
        description: '{{ doc("milestone_title") }}'
      - name: milestone_due_date
        description: '{{ doc("milestone_due_date") }}'
      - name: issue_epic_labels
        description: Array of labels applied to the issue or epic.
      - name: deliverable
        description: '{{ doc("issue_deliverable") }}'
      - name: product_group_extended
        description: '{{ doc("issue_product_group_extended") }}'
      - name: product_group
        description: '{{ doc("issue_product_group") }}'
      - name: product_category
        description: '{{ doc("issue_product_category") }}'
      - name: product_stage
        description: '{{ doc("issue_product_stage") }}'
      - name: is_user_request_only_in_collaboration_project
        description: If TRUE means that the issue / epic user request is ONLY found in the customer collaboration project, which means the priority request_prioty will always be one, and not in an issue / epic comment or description in `gitlab-org`.
      - name: link_last_updated_at
        description: Timestamp for the last updated time of the comment / description where the SFDC / Zendesk link was found in the issue / epic user request. In case the user request was only found in the customer collaboration project, it refers to the last time that the issue / epic request was found in the customer collaboration project.
      - name: crm_account_next_renewal_month
        description: CRM Account next renewal month based on Zuora subscription and charge information. If NULL it means that either the renewal month has passed or the account didn't have one.
      - name: customer_reach
        description: CRM Account amount of seats in the current month based on Zuora subscription and charge information.
      - name: crm_account_open_opp_net_arr
        description: Sum of Net ARR for all currently open SFDC opportunities for the CRM Account.
      - name: crm_account_open_opp_net_arr_fo
        description: Sum of Net ARR for all currently open SFDC opportunities for the CRM Account with order type New First Order.
      - name: crm_account_open_opp_net_arr_growth
        description: Sum of Net ARR for all currently open SFDC opportunities for the CRM Account with order type New Connected and Growth.
      - name: opportunity_reach
        description: Count of aggregate prospect licenses from open SFDC opportunities, where prospect means New First Order opportunities. The amount of seats in the opportunity are fetched from the primary quote linked to the opportunity.
      - name: crm_account_lost_opp_net_arr
        description: For the CRM Account, sum of all Net ARR where the prospect was lost. Where prospect means New First Order opportunities.
      - name: crm_account_lost_customer_arr
        description: For the CRM Account, sum of all ARR lost when the customer left GitLab.
      - name: lost_arr
        description: Sum of crm_account_lost_opp_arr and crm_account_lost_customer_arr
      - name: theme_labels
        description: '{{ doc("issue_theme_labels") }}'
      - name: primary_solution_architect_id
        description: The primary solution architecht user id associated with the SFDC opportunity, whenever there is an opportunity linked to the user request.
      - name: primary_solution_architect_user_name
        description: The primary solution architecht user name associated with the SFDC opportunity, whenever there is an opportunity linked to the user request.

  - name: mart_license_utilization_daily
    description: '{{ doc("mart_license_utilization_daily") }}'
    columns:
      - name: report_date
        description: '{{ doc("report_date") }}'
      - name: dim_installation_id
        description: '{{ doc("dim_installation_id") }}'
      - name: dim_namespace_id
        description: '{{ doc("dim_namespace_id") }}'
      - name: dim_subscription_id
        description: '{{ doc("dim_subscription_id") }}'
      - name: dim_subscription_id_original
        description: '{{ doc("dim_subscription_id_original") }}'
      - name: dim_crm_account_id
        description: '{{ doc("dim_crm_account_id") }}'
      - name: assignable_feature_set
        description: '{{ doc("assignable_feature_set") }}'
      - name: assignable_feature_set_clean
        description: '{{ doc("assignable_feature_set_clean") }}'
      - name: dim_product_tier_id
        description: '{{ doc("dim_product_tier_id") }}'
      - name: product_deployment_type
        description: '{{ doc("product_deployment_type") }}'
      - name: product_tier_name
        description: '{{ doc("product_tier_name") }}'
      - name: is_duo_pro_trial
        description: Flag indicating if the record represents a Duo Pro trial
      - name: is_duo_enterprise_trial
        description: Flag indicating if the record represents a Duo Enterprise trial
      - name: namespace_is_internal
        description: '{{ doc("namespace_is_internal") }}'
      - name: is_max_billable_instance_for_subscription
        description: Flag indicating if this is the instance with the maximum billable users for the subscription
      - name: instance_type
        description: '{{ doc("instance_type") }}'
      - name: instance_type_ordering_field
        description: Numeric field for ordering instance types (1=Production, 2=Non-Production, 3=Unknown, 4=Other)
      - name: health_score_ordering_field
        description: Numeric field for ordering health score inclusion (1=Included, 2=Opt-Out, 3=NULL)
      - name: license_users_source
        description: '{{ doc("license_users_source") }}'
      - name: billable_users_source
        description: '{{ doc("billable_users_source") }}'
      - name: license_users
        description: '{{ doc("license_user_count") }}'
      - name: billable_users
        description: '{{ doc("billable_user_count") }}'
      - name: utilization_rate
        description: '{{ doc("license_utilization") }}'
