version: 2

models:
  - name: mart_available_to_renew_variance
    description: '{{ doc("mart_available_to_renew_variance") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - fiscal_quarter_name_fy
            - dim_crm_account_id
    columns:
        - name: fiscal_quarter_name_fy
        - name: dim_crm_account_id
        - name: available_to_renew
        - name: arr_basis


  - name: mart_processed_refunds_monthly
    description: '{{ doc("mart_processed_refunds_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
            - unique
        - name: refund_amount
          description: Sum of refund amounts per period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_processed_iia_monthly
    description: '{{ doc("mart_processed_iia_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
            - unique

  - name: mart_payments_refunds_against_future_invoices
    description: '{{ doc("mart_payments_refunds_against_future_invoices") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
            - unique
        - name: payments_refunds_against_future_invoices
          description: Sum of payment and refund amounts made for future dated invoices
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_processed_cba_monthly
    description: '{{ doc("mart_processed_cba_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
            - unique
        - name: increase
          description: Sum of increased credit balance
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]
        - name: decrease
          description: Sum of decreased credit balance
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_historical_balance_by_payment_terms_bucket_monthly
    description: '{{ doc("mart_historical_balance_by_payment_terms_bucket_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
        - name: balance
          description: Open balance in period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_invoices_in_preview_monthly
    description: '{{ doc("mart_invoices_in_preview_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
            - unique
        - name: pending_invoice_amount
          description: Sum of pending amounts
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]
        - name: pending_invoice_count
          description: Count of pending invoices
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ] 

  - name: mart_ar_per_ssp_channel_monthly
    description: '{{ doc("mart_ar_per_ssp_channel_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
        - name: channel
          description: channel type
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]
        - name: total_balance_per_channel
          description: Balance amount per channel
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ] 

  - name: mart_payment_type_monthly
    description: '{{ doc("mart_payment_type_monthly") }}'
    columns:
        - name: period
          description: Accounting period
          data_tests:
            - not_null
        - name: total_payment_amount
          description: payment amount
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_current_ar_by_aging_payment_terms
    description: '{{ doc("mart_current_ar_by_aging_payment_terms") }}'
    columns:
        - name: dim_invoice_id
          data_tests:
            - not_null
            - unique
          tags: [ "tdf", "zuora" ]     
        - name: balance
          data_tests:
            - not_null   

  - name: mart_booking_by_order_type_monthly
    description: '{{ doc("mart_booking_by_order_type_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ] 
        - name: subscription_type
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]    

  - name: mart_booking_by_payment_schedule_opportunity_category_monthly
    description: '{{ doc("mart_booking_by_payment_schedule_opportunity_category_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   
        - name: standard_booking_count
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   

  - name: mart_collections_monthly
    description: '{{ doc("mart_collections_monthly") }}'
    columns:
        - name: payment_period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   
        - name: billed_period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]    

  - name: mart_cdot_invoices_manual_intervention_monthly
    description: '{{ doc("mart_cdot_invoices_manual_intervention_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
            - unique
          tags: [ "tdf", "zuora" ]   
        - name: count_all_cdot_invoices
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]

  - name: mart_public_sector_ar_monthly
    description: '{{ doc("mart_public_sector_ar_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   
        - name: total_balance_per_segment
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   

  - name: mart_web_direct_vs_sales_assisted_ar_monthly
    description: '{{ doc("mart_web_direct_vs_sales_assisted_ar_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   
        - name: total_balance_per_path
          data_tests:
            - not_null
          tags: [ "tdf", "zuora" ]   

  - name: mart_booking_billing_ar_monthly
    description: '{{ doc("mart_booking_billing_ar_monthly") }}'
    columns:
        - name: period
          data_tests:
            - not_null
            - unique
          tags: [ "tdf", "zuora" ]   

