version: 2

sources:
  - name: runner_usage
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: runner_usage
    loader: S3

    quoting:
      database: true
      schema: false
      identifier: false

    tables:
      - name: runner_logs
        description: "log data from dedicated runners"
        external:
          location: "@raw.public.s3_runner_usage_test"
          file_format: "( type = json )"
          auto_refresh: false
          partitions:
            - name: customer
              data_type: varchar
              expression: split_part(metadata$filename, '/', 1)
            - name: runner
              data_type: varchar
              expression: split_part(metadata$filename, '/', 2)
            - name: _year
              data_type: int
              expression: split_part(metadata$filename, '/', 4)
            - name: _month
              data_type: int
              expression: split_part(metadata$filename, '/', 5)
            - name: _day
              data_type: int
              expression: split_part(metadata$filename, '/', 6)